apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: docker.io/achalpadol/react-rust-post-db:v2

          ports:
            - containerPort: 3306

          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app3-config
                  key: MYSQL_DATABASE

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_ROOT_PASSWORD

    
